# Generated by Django 3.2.7 on 2021-09-14 00:11

from django.db import migrations, models
import picturic.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', picturic.fields.PictureField(upload_to=picturic.fields.PictureField._upload_to_path)),
            ],
        ),
    ]
