# Generated by Django 3.2.7 on 2021-09-28 21:35

from django.db import migrations, models
import django.db.models.deletion
import picturic.fields
import picturic.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('picturic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureGeneric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', picturic.fields.PictureField(upload_to=picturic.utils.upload_to_path_generic)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='PictureModel',
        ),
    ]
