# Generated by Django 3.2.7 on 2021-09-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
