# Generated by Django 3.2.8 on 2021-10-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0003_comment_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
