# Generated by Django 3.2.7 on 2021-09-11 19:15

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='IR', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-z0-9_]+$', message='Username can have [A-Z, a-z, 0-9, _] chars only.'), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
