# Generated by Django 3.2.7 on 2021-09-23 15:22

from django.db import migrations
import picturic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210911_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=picturic.fields.PictureField(blank=True, default='defaults/customer_profile/cat.jpg', upload_to=picturic.fields.PictureField._upload_to_path),
        ),
    ]
